public final class de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt extends java.lang.Object
{

    private static final void tryCatchExample1()
    {
        java.io.PrintStream $stack3, $stack5;
        java.lang.NoSuchFieldException $stack4;
        java.lang.NoSuchMethodException $stack2;

     label1:
        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("Ranjith");

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid2(java.lang.String)>("ranj345n");

     label2:
        goto label5;

     label3:
        $stack4 := @caughtexception;

        $stack5 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack5.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample1 (NoSuchFieldException)");

        goto label5;

     label4:
        $stack2 := @caughtexception;

        $stack3 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack3.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample1 (NoSuchMethodException)");

     label5:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
        catch java.lang.NoSuchMethodException from label1 to label2 with label4;
    }

    private static final void tryCatchExample2()
    {
        java.io.PrintStream $stack3;
        java.lang.NoSuchFieldException $stack2;

     label1:
        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("Ranjith");

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("ranj345n");

     label2:
        goto label4;

     label3:
        $stack2 := @caughtexception;

        $stack3 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack3.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample2 (NoSuchFieldException)");

     label4:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
    }

    private static final void tryCatchExample3()
    {
        java.io.PrintStream $stack2, $stack4, $stack6, $stack7, $stack9, $stack10;
        java.lang.Throwable $stack3;
        java.lang.NoSuchMethodException $stack5;
        java.lang.NoSuchFieldException $stack8;

     label1:
        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("Ranjith");

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid2(java.lang.String)>("ranj345n");

     label2:
        $stack2 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample3");

        goto label9;

     label3:
        $stack8 := @caughtexception;

        $stack9 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack9.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample3 (NoSuchFieldException)");

     label4:
        $stack10 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack10.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample3");

        goto label9;

     label5:
        $stack5 := @caughtexception;

        $stack6 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack6.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample3 (NoSuchMethodException)");

     label6:
        $stack7 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack7.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample3");

        goto label9;

     label7:
        $stack3 := @caughtexception;

     label8:
        $stack4 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack4.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample3");

        throw $stack3;

     label9:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
        catch java.lang.NoSuchMethodException from label1 to label2 with label5;
        catch java.lang.Throwable from label1 to label2 with label7;
        catch java.lang.Throwable from label3 to label4 with label7;
        catch java.lang.Throwable from label5 to label6 with label7;
        catch java.lang.Throwable from label7 to label8 with label7;
    }

    private static final void tryCatchExample4()
    {
        java.io.PrintStream $stack2, $stack4;
        java.lang.Throwable $stack3;

     label1:
        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("Ranjith");

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid2(java.lang.String)>("ranj345n");

     label2:
        $stack2 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample4");

        goto label5;

     label3:
        $stack3 := @caughtexception;

     label4:
        $stack4 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack4.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample4");

        throw $stack3;

     label5:
        return;

        catch java.lang.Throwable from label1 to label2 with label3;
        catch java.lang.Throwable from label3 to label4 with label3;
    }

    private static final int tryCatchExample5()
    {
        java.io.PrintStream $stack3, $stack5, $stack7, $stack8, $stack11, $stack12;
        java.lang.Throwable $stack4;
        java.lang.NoSuchMethodException $stack6;
        short l0;
        java.lang.NoSuchFieldException $stack10;

     label1:
        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid1(java.lang.String)>("Ranjith");

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void checkValid2(java.lang.String)>("ranj345n");

        l0 = 0;

     label2:
        $stack3 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack3.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample5");

        goto label9;

     label3:
        $stack10 := @caughtexception;

        $stack11 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack11.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample3 (NoSuchFieldException)");

        l0 = -100;

     label4:
        $stack12 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack12.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample5");

        goto label9;

     label5:
        $stack6 := @caughtexception;

        $stack7 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack7.<java.io.PrintStream: void println(java.lang.Object)>("Something went wrong in tryCatchExample3 (NoSuchMethodException)");

        l0 = -150;

     label6:
        $stack8 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack8.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample5");

        goto label9;

     label7:
        $stack4 := @caughtexception;

     label8:
        $stack5 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack5.<java.io.PrintStream: void println(java.lang.Object)>("Finally executed in tryCatchExample5");

        throw $stack4;

     label9:
        return l0;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
        catch java.lang.NoSuchMethodException from label1 to label2 with label5;
        catch java.lang.Throwable from label1 to label2 with label7;
        catch java.lang.Throwable from label3 to label4 with label7;
        catch java.lang.Throwable from label5 to label6 with label7;
        catch java.lang.Throwable from label7 to label8 with label7;
    }

    private static final void checkValid1(java.lang.String) throws java.lang.NoSuchFieldException
    {
        java.lang.CharSequence l1;
        java.lang.NoSuchFieldException $stack5;
        java.lang.String name;
        kotlin.text.Regex $stack3;
        boolean $stack4;

        name := @parameter0: java.lang.String;

        l1 = (java.lang.CharSequence) name;

        $stack3 = new kotlin.text.Regex;

        specialinvoke $stack3.<kotlin.text.Regex: void <init>(java.lang.String)>(".*\\d.*");

        $stack4 = virtualinvoke $stack3.<kotlin.text.Regex: boolean matches(java.lang.CharSequence)>(l1);

        if $stack4 == 0 goto label1;

        $stack5 = new java.lang.NoSuchFieldException;

        specialinvoke $stack5.<java.lang.NoSuchFieldException: void <init>(java.lang.String)>("Invalid name");

        throw $stack5;

     label1:
        return;
    }

    private static final void checkValid2(java.lang.String) throws java.lang.NoSuchMethodException
    {
        java.lang.CharSequence l1;
        java.lang.NoSuchMethodException $stack5;
        java.lang.String name;
        kotlin.text.Regex $stack3;
        boolean $stack4;

        name := @parameter0: java.lang.String;

        l1 = (java.lang.CharSequence) name;

        $stack3 = new kotlin.text.Regex;

        specialinvoke $stack3.<kotlin.text.Regex: void <init>(java.lang.String)>(".*\\d.*");

        $stack4 = virtualinvoke $stack3.<kotlin.text.Regex: boolean matches(java.lang.CharSequence)>(l1);

        if $stack4 == 0 goto label1;

        $stack5 = new java.lang.NoSuchMethodException;

        specialinvoke $stack5.<java.lang.NoSuchMethodException: void <init>(java.lang.String)>("Invalid name");

        throw $stack5;

     label1:
        return;
    }

    public static final void main()
    {
        java.io.PrintStream $stack6;
        int $stack3;
        java.lang.StringBuilder $stack1, $stack2, $stack4;
        java.lang.String $stack5;

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void tryCatchExample1()>();

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void tryCatchExample2()>();

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void tryCatchExample3()>();

        $stack1 = new java.lang.StringBuilder;

        specialinvoke $stack1.<java.lang.StringBuilder: void <init>()>();

        $stack2 = virtualinvoke $stack1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("tryCatchExample5() return ");

        $stack3 = staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: int tryCatchExample5()>();

        $stack4 = virtualinvoke $stack2.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($stack3);

        $stack5 = virtualinvoke $stack4.<java.lang.StringBuilder: java.lang.String toString()>();

        $stack6 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $stack6.<java.io.PrintStream: void println(java.lang.Object)>($stack5);

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void tryCatchExample4()>();

        return;
    }

    public static void main(java.lang.String[])
    {
        java.lang.String[] args;

        args := @parameter0: java.lang.String[];

        staticinvoke <de.fraunhofer.iem.basics.exceptions.KotlinTryCatchFinallyKt: void main()>();

        return;
    }
}
